# Generated by Django 5.0.6 on 2024-05-17 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallblog', '0002_remove_comment_created_at_remove_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='smallblog.post'),
        ),
    ]
